### ISSUE TITLE
Question: cannot reproduce a figure in Chapter 2

### ISSUE THREAD

**Issue by lrnilingy** [EdwardRaff/Inside-Deep-Learning#22]
Hi @EdwardRaff - I am a beginner and currently working through Chapter 2.  On print book's P49, there is a figure:
<img width="598" alt="image" src="https://github.com/EdwardRaff/Inside-Deep-Learning/assets/26152378/6b1f57cc-15c7-4b34-8f7e-22b143a8d54e">

I am using the code in this repo and my pytorch is v2.0.1

The figure I got is:
<img width="529" alt="image" src="https://github.com/EdwardRaff/Inside-Deep-Learning/assets/26152378/4746f936-17af-41fc-a99b-0fde19b3eee2">

Can you advise what's going wrong?

Thank you.

**Comment by EdwardRaff** [comment]
Nothing is going wrong in particular. This is a "reproducibility" problem, where PyTorch is not very good at allowing you to get the exact same outputs given the same inputs. I tried to make the code examples relatively robust to this problem, but as PyTorch keeps updating and small things change in various little places, eventually, something sometimes "breaks." 

The bigger lesson here is that sometimes you can do everything that was said and get a different answer because important details in the underlying tools you are using may be changing!
